<ul id="menu" class="page-sidebar-menu">

    <li {!! (Request::is('admin') ? 'class="active"' : '') !!}>
        <a href="{{ route('admin.dashboard') }}">
            <i class="fa fa-home" aria-hidden="true"></i>&nbsp;
            <span class="title fs-15">Dashboard</span>
        </a>
    </li>

    <li {!! (Request::is("admin/events") || Request::is('admin/events/*') || Request::is('admin/checkin_checkout/*') || Request::is('admin/preemptions/*') ? 'class="active"' : '') !!}>
        <a href="{{  URL::to('admin/events') }}">
            <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;
            <span class="title fs-15">จัดการ Event</span>
        </a>
    </li>

    <?php if (Sentinel::getUser()->status_process == 0) {?>
      <li {!! (Request::is('admin/users') || Request::is('admin/users/*') ? 'class="active""' : '') !!}>
          <a href="{{  URL::to('admin/users') }}" >
              <i class="fa fa-user" aria-hidden="true"></i>&nbsp;
              <span class="title fs-15">จัดการผู้ดูแลระบบ</span>
          </a>
      </li>

      <li {!! (Request::is('admin/ManagementModalAndType/show') || Request::is('admin//ManagementModalAndType/*') ? 'class="active""' : '') !!}>
          <a href="{{  URL::to('admin/ManagementModalAndType/show') }}" >
              <i class="fa fa-car" aria-hidden="true"></i>&nbsp;
              <span class="title fs-15">จัดการ Model และ Type</span>
          </a>
      </li>
  <?php  }?>





    <!-- <li {!! (Request::is('admin/reports') || Request::is('admin/events/1/checkin_checkout_report') || Request::is('admin/events/1/preemption_report') || Request::is('admin/events/1/sale_dealer_report') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="fa fa-user" aria-hidden="true"></i>&nbsp;
            <span class="title fs-15">รายงาน</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('admin/events/1/checkin_checkout_report') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/events/1/checkin_checkout_report') }}">
                    <i class="fa fa-angle-double-right"></i>
                    รายงานการ CHECK-IN / CHECK-OUT
                </a>
            </li>
            <li {!! (Request::is('admin/events/1/preemption_report') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/events/1/preemption_report') }}">
                    <i class="fa fa-angle-double-right"></i>
                    รายงานใบจอง
                </a>
            </li>
            <li {!! (Request::is('admin/events/1/sale_dealer_report') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/events/1/sale_dealer_report') }}">
                    <i class="fa fa-angle-double-right"></i>
                    รายงานข้อมูลของ Sale Dealer
                </a>
            </li>
        </ul>
    </li> -->





    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>
